from enum import Enum

class CmdTypes(Enum):
    """
    Category enumeration of registered commands.
    
    When an unclassified command appears, expand the enumeration first.
    """
    LISTEN_ALL = "LISTEN_ALL"
    ECHO = "ECHO"
    CHAT = "CHAT"
    FIM = "FIM"
    CONTEXT = "CONTEXT"
    GENIMG = "GENIMG"
    PROMPT = "PROMPT"
    CONFIG = "CONFIG"
    MIXED = "MIXED"
    BRANCH = "BRANCH"
    BRANCH_CONTEXT = "BRANCH.CONTEXT"
    BRANCH_PROMPT = "BRANCH.PROMPT"
    BRANCH_CONFIG = "BRANCH.CONFIG"
    BRANCH_MIXED = "BRANCH.MIXED"
    USERFILE = "USERFILE"
    RESERVED = "RESERVED"
    TEMPLATE = "TEMPLATE"
    SEE_CMD = "SEE_CMD"
    RENDER = "RENDER"
    MODEL = "MODEL"
    VERSION = "VERSION"
    SIMILARITY = "SIMILARITY"
    SEQUENCE = "SEQUENCE"
    CONTROL = "CONTROL"
    VARIABLE = "VARIABLE"
    LICENSES = "LICENSES"
    NEXUS = "NEXUS"
    STATUS = "STATUS"
    SENDMSG = "SENDMSG"
    NAMESPACE = "NAMESPACE"
    STATISTIC = "STATISTIC"
    GAMES = "GAMES"
    CLIENT_CONFIG = "CLIENT_CONFIG"
    OTHER = "OTHER"